name: greengage7

x-greengagedb-node: &greengagedb-node
  platform: linux/amd64
  build:
    context: .
    platforms:
      - linux/amd64
  image: greengagedb7-node
  init: true
  command: /usr/sbin/sshd -D
  domainname: example.com
  sysctls:
    kernel.sem: "500 1024000 200 4096"

services:
  cdw:
    <<: *greengagedb-node
    container_name: cdw
    hostname: cdw
    ports:
      - "5432:5432"
    volumes:
      - ${EXAMPLES_DIR:-./examples}:/home/gpadmin/examples
      - ./configs/pxf/servers:/home/gpadmin/pxf-servers:ro
      - ./configs/hostfile_all_hosts:/home/gpadmin/hostfile_all_hosts
      - ./configs/hostfile_segment_hosts:/home/gpadmin/hostfile_segment_hosts
      - ./configs/init_config:/home/gpadmin/init_config
      - ./configs/.bashrc:/home/gpadmin/.bashrc
      - cdw_data:/data1
      - cdw_home:/home/gpadmin
    networks:
      cluster_network:
        ipv4_address: 192.168.1.10

  scdw:
    <<: *greengagedb-node
    container_name: scdw
    hostname: scdw
    volumes:
      - ./configs/.bashrc:/home/gpadmin/.bashrc
      - scdw_data:/data1
      - scdw_home:/home/gpadmin
    networks:
      cluster_network:
        ipv4_address: 192.168.1.20

  sdw1:
    <<: *greengagedb-node
    container_name: sdw1
    hostname: sdw1
    volumes:
      - ./configs/.bashrc:/home/gpadmin/.bashrc
      - sdw1_data:/data1
      - sdw1_home:/home/gpadmin
    networks:
      cluster_network:
        ipv4_address: 192.168.1.30

  sdw2:
    <<: *greengagedb-node
    container_name: sdw2
    hostname: sdw2
    volumes:
      - ./configs/.bashrc:/home/gpadmin/.bashrc
      - sdw2_data:/data1
      - sdw2_home:/home/gpadmin
    networks:
      cluster_network:
        ipv4_address: 192.168.1.40

volumes:
  cdw_data:
  cdw_home:
  scdw_data:
  scdw_home:
  sdw1_data:
  sdw1_home:
  sdw2_data:
  sdw2_home:

networks:
  cluster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/20
